function [RightFistOP, LeftFistOP, WaistOP, RightFootOP, LeftFootOP] = ReadOpticalRawData(OPFolder, ActNum)
    LeftFistOPA  = readmatrix( append(OPFolder, '/LWRA_S', ActNum, '.csv'));
    LeftFistOPB  = readmatrix( append(OPFolder, '/LWRB_S', ActNum, '.csv'));
    RightFistOPA = readmatrix( append(OPFolder, '/RWRA_S', ActNum, '.csv'));
    RightFistOPB = readmatrix( append(OPFolder, '/RWRB_S', ActNum, '.csv'));
    RightFootOP = readmatrix( append(OPFolder, '/RHEE_S', ActNum, '.csv'));
    LeftFootOP  = readmatrix( append(OPFolder, '/LHEE_S', ActNum, '.csv'));
    RWaistOP    = readmatrix( append(OPFolder, '/RPSI_S', ActNum, '.csv'));
    LWaistOP    = readmatrix( append(OPFolder, '/LPSI_S', ActNum, '.csv'));
    LeftFistOPA = LeftFistOPA(:,1:3);
    LeftFistOPB = LeftFistOPB(:,1:3);
    RightFistOPA = RightFistOPA(:,1:3);
    RightFistOPB = RightFistOPB(:,1:3);
    RightFootOP = RightFootOP(:,1:3);
    LeftFootOP = LeftFootOP(:,1:3);
    RWaistOP = RWaistOP(:,1:3);
    LWaistOP = LWaistOP(:,1:3);
    LeftFistOPA(isnan(LeftFistOPA))=0;
    LeftFistOPB(isnan(LeftFistOPB))=0;
    RightFistOPA(isnan(RightFistOPA))=0;
    RightFistOPB(isnan(RightFistOPB))=0;
    RightFootOP(isnan(RightFootOP))=0;
    LeftFootOP(isnan(LeftFootOP))=0;
    RWaistOP(isnan(RWaistOP))=0;
    LWaistOP(isnan(LWaistOP))=0;
    LeftFistOP = (LeftFistOPA + LeftFistOPB) / 2;
    RightFistOP = (RightFistOPA + RightFistOPB) / 2;
    WaistOP = (RWaistOP + LWaistOP) / 2;
end